### ISSUE TITLE
[Ontology] Ferdigstille ontologi

### ISSUE THREAD

**Issue by stigbd** [Informasjonsforvaltning/skos-ap-no-begrep#10]
skosno-turtle.owl er ikkje ferdig. Vi må gjere noko for å løfte denne til første versjon.

**Comment by jimjyang** [comment]
+ prefix til skosno (URI) må oppdateres etter at URIen er fastsatt og implementert.

**Comment by OyvindLGjesdal** [comment]
Hei @jimjyang  og @stigbd 

Ser på ontologien, og lurer på om en har tenkt til å ha en  annotation type ala rdfs:label med language tag(s) som gjerne kan bruke samme verdi som siste del av uri og en oversetting til norsk om det er en ekstern term? Tenker på om en ønsker å bruke ontologien i en visning.

Veldig fint med både eksempel og definisjon synlig .

**Comment by jimjyang** [comment]
> Ser på ontologien, og lurer på om en har tenkt til å ha en annotation type ala rdfs:label med language tag(s) som gjerne kan bruke samme verdi som siste del av uri og en oversetting til norsk om det er en ekstern term? Tenker på om en ønsker å bruke ontologien i en visning.

@OyvindLGjesdal Kan du gi noen eksempler?

**Comment by OyvindLGjesdal** [comment]
Eg tenker i første omgang på vokabular(klasser og egenskaper) som ikke har rdfs:labels, og importert vokabular som kun har engelske labels.

For noe av vokabularet som er importert er det med rdfs:label med engelsk språktag, som for `dcterms:audience`, men en kan også ta med egne navn for bokmål (hentet fra SKOS-AP-NO-Begrep 1.1)

``` 
###  http://purl.org/dc/terms/audience
terms:audience rdf:type owl:ObjectProperty ;
               rdfs:range terms:AgentClass ;
               rdfs:comment "A class of entity for whom the resource is intended or useful."@en ;
               rdfs:isDefinedBy terms: ;
               rdfs:label "audience"@en ;
               rdfs:label "målgruppe"@nb; 
               rdfs:label "målgruppe"@nn.
```  


I skosnos utvidede vokabular har jeg ikke sett rdfs:label på propeties (har ikke sjekket om dette er gjennomgående). Der kunne en bruke eget  navn i vanlig form for eksempel:  

```
skosno:forholdTilKilde rdfs:label "forhold til kilde"@nb.`
```

**Comment by stigbd** [comment]
Takk for innspel. Dette er ein god idé som vi vil ta med inn når vi førebur ontologien for publisering.
