### ISSUE TITLE
[Ontology] Ferdigstille shacl-regler for validering

### ISSUE THREAD

**Issue by stigbd** [Informasjonsforvaltning/skos-ap-no-begrep#11]
BegrepShape.ttl er eit godt utgangspunkt, men vi må implementere alle regler som ligger i https://doc.difi.no/data/forvaltningsstandard-begrepsbeskrivelser/#vedlegga

**Comment by sskagemo** [comment]
Merk at det er feil i standarden https://doc.difi.no/data/begrep-skos-ap-no/ for prefLabel, altLabel og hiddenLabel, der det står at de alle har datatype "Literal", men det er påkrevet med en skosxl:Label. Det bør gjenspeiles i shacl-reglene.

**Comment by stigbd** [comment]
Her bør vi vurdere å skille shacl ut i egen folder, analogt til dcat-ap-no.

**Comment by jimjyang** [comment]
Ja, i en egen folder.
