### ISSUE TITLE
[Ontology] Publisering i maskinlesbart format (RDF)

### ISSUE THREAD

**Issue by jimjyang** [Informasjonsforvaltning/skos-ap-no-begrep#49]
I tillegg til html, bør ontologien (i hvert fall skosno-definisjonene) publiseres i maskinlesbart format, bl.a. for å muliggjøre validering.

**Comment by stigbd** [comment]
Denne skal no vere publisert no på https://data.norge.no/vocabulary/skosno

**Comment by jimjyang** [comment]
Fiksa
