### ISSUE TITLE
[Standard] skosno:forholdTilKilde ser ut til å vere ein property som her har ein annan property som verdi.

### ISSUE THREAD

**Issue by stigbd** [Informasjonsforvaltning/skos-ap-no-begrep#54]
skosno:forholdTilKilde ser ut til å vere ein property som her har ein annan property som verdi. Det hadde vore fint med ein definsjon av domain og range av skosno:forholdTilKilde.

_Originally posted by @stigbd in https://github.com/difi/skos-ap-no/pull/53_

**Comment by jimjyang** [comment]
Tas ifm. neste større omstrukturering av standarden.

**Comment by jimjyang** [comment]
Hensyntatt i høringsversjonen
